using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;



namespace Adventure_Server_CSharp
{

    public enum ClientPackets
    {
   
        PACKET_SERVERJOIN = 21816,
        PACKET_LOGIN = 0,
        PACKET_RESPAWNHERE = 18,
        PACKET_RESPAWNSAFEZONE = 274,
        PACKET_ATKDATA = 65,
        PACKET_UNKNOWN = 7,
        PACKET_LOOTITEM = 345,
        PACKET_GIVESTR = 195,
        PACKET_GIVEDEX = 451,
        PACKET_GIVEINT = 707,
        PACKET_LOGINACCEPTANDCHANNELSELECT = 512,
        PACKET_JOINCHANNEL = 1024,
        PACKET_JOINCHANNELACCEPT = 257,
        PACKET_STARTGAMEBUTTON = 1281,
        PACKET_LOADINGSCREEN = 610,
        PACKET_LOADINGSCREENUNKNOWN = 59399,
        PACKET_PLAYERPOSITIONINFO = 1341,  // PLAYER MAP + POS INFO BUNU YAPINCA HARİTA AÇILIYO LOADING %100 OLUYOR OYUN BAŞLIYOR
        PACKET_CHATINFOWITHSLASH = 1905,
        PACKET_LOADINGUNKNOWN2 = 21767,
        PACKET_CHARACTERSPAWN = 21796,
        PACKET_MOVEREQUEST = 290,
        PACKET_MOVERUNSWIFTREQUEST = 546,
        PACKET_MOVEFLY = 1062,
        PACKET_CHATMSG = 369,
        PACKET_ITEMUSAGE = 1113, // HEPSI AYNI OLMAYABİLİR | 4185
        PACKET_SWITCHWEAPON = 1369,
        PACKET_DEFMODE = 67,
        PACKET_UPGRADEITEM = 596,
        PACKET_PARTYREQ = 338,// AA 55 04 00 52 01 00 03 55 AA 
        PACKET_PARTYREQ_ANSWER = 594,// AA 55 03 00 52 02 01 55 AA SONDAKI 01 KABUL EDIP ETMEDIGI
        PACKET_PARTY_DISBAND = 850,
        PACKET_ATTMODE = 323,
        PACKET_MEDITATION = 1410,
        PACKET_ADDFRIEND = 971,
        PACKET_TELEPORT = 4392,
        PACKET_ITEMDROP = 601,
        PACKET_ITEMDRAG = 857,
        PACKET_ITEMCOMBINE = 1625,
        PACKET_ITEMSEPERATE = 2393,
        PACKET_ITEMSELL = 600,
        PACKET_UNKQUIT = 600,
        PACKET_CREATECHARACTER = 769,
        PACKET_REQUESTCHARACTERMENU = 513,
        PACKET_DELETECHARACTER = 45569,
        PACKET_DELETECHARACTER2 = 1025,
        PACKET_SELECTCHARACTER = 2313,
        PACKET_SELECTSERVER = 2057,
        PACKET_ITEMDESTROY = 12377,
        PACKET_AIMONENEMY = 27087,
        PACKET_AIMONME = 19663,
        PACKET_FIRSTATTACK = 321, //256şar bir şekilde artarak ilerliyor.
        PACKET_OPENNPCWINDOW = 343,
        PACKET_OPENNPCSHOP = 599,
        PACKET_AFTERSPAWNUNK = 295,
        PACKET_BUYITEMREQUEST = 344,
        PACKET_ITEMSWITCHREQUEST = 1881,
        PACKET_MAPCHANGE = 62760,
        PACKET_BOWATTACK1 = 69,
        PACKET_BOWATTACK2 = 325,
        PACKET_PKON = 299,
        PACKET_PKOFF = 43,

        PACKET_DUMMY = 21784,

        // SKILLS

        PACKET_UPGRADESKILL = 641,
        PACKET_UPGRADEPASSIVESKILL = 642,
        PACKET_DELETESKILLBOOK = 1153,

        // STATS //

        PACKET_STRADD = 196,
        PACKET_DEXADD = 452,
        PACKET_INTADD = 708,

        PACKET_CHANGEMAP1 = 21875,
        PACKET_CHANGEMAP2 = 21916,

        PACKET_CHANGEMAP4 = 7975,

    }

}
